// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: sending.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileUploadServiceClient is the client API for FileUploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileUploadServiceClient interface {
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileUploadService_UploadFileClient, error)
	DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (FileUploadService_DownloadFileClient, error)
	GetListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (FileUploadService_GetListFilesClient, error)
}

type fileUploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileUploadServiceClient(cc grpc.ClientConnInterface) FileUploadServiceClient {
	return &fileUploadServiceClient{cc}
}

func (c *fileUploadServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileUploadService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileUploadService_ServiceDesc.Streams[0], "/v1.FileUploadService/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileUploadServiceUploadFileClient{stream}
	return x, nil
}

type FileUploadService_UploadFileClient interface {
	Send(*FileUploadRequest) error
	CloseAndRecv() (*FileUploadResponse, error)
	grpc.ClientStream
}

type fileUploadServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *fileUploadServiceUploadFileClient) Send(m *FileUploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileUploadServiceUploadFileClient) CloseAndRecv() (*FileUploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileUploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileUploadServiceClient) DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (FileUploadService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileUploadService_ServiceDesc.Streams[1], "/v1.FileUploadService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileUploadServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileUploadService_DownloadFileClient interface {
	Recv() (*FileDownloadResponse, error)
	grpc.ClientStream
}

type fileUploadServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *fileUploadServiceDownloadFileClient) Recv() (*FileDownloadResponse, error) {
	m := new(FileDownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileUploadServiceClient) GetListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (FileUploadService_GetListFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileUploadService_ServiceDesc.Streams[2], "/v1.FileUploadService/GetListFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileUploadServiceGetListFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileUploadService_GetListFilesClient interface {
	Recv() (*ListFilesResponse, error)
	grpc.ClientStream
}

type fileUploadServiceGetListFilesClient struct {
	grpc.ClientStream
}

func (x *fileUploadServiceGetListFilesClient) Recv() (*ListFilesResponse, error) {
	m := new(ListFilesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileUploadServiceServer is the server API for FileUploadService service.
// All implementations must embed UnimplementedFileUploadServiceServer
// for forward compatibility
type FileUploadServiceServer interface {
	UploadFile(FileUploadService_UploadFileServer) error
	DownloadFile(*FileDownloadRequest, FileUploadService_DownloadFileServer) error
	GetListFiles(*ListFilesRequest, FileUploadService_GetListFilesServer) error
	mustEmbedUnimplementedFileUploadServiceServer()
}

// UnimplementedFileUploadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileUploadServiceServer struct {
}

func (UnimplementedFileUploadServiceServer) UploadFile(FileUploadService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileUploadServiceServer) DownloadFile(*FileDownloadRequest, FileUploadService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedFileUploadServiceServer) GetListFiles(*ListFilesRequest, FileUploadService_GetListFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetListFiles not implemented")
}
func (UnimplementedFileUploadServiceServer) mustEmbedUnimplementedFileUploadServiceServer() {}

// UnsafeFileUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileUploadServiceServer will
// result in compilation errors.
type UnsafeFileUploadServiceServer interface {
	mustEmbedUnimplementedFileUploadServiceServer()
}

func RegisterFileUploadServiceServer(s grpc.ServiceRegistrar, srv FileUploadServiceServer) {
	s.RegisterService(&FileUploadService_ServiceDesc, srv)
}

func _FileUploadService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileUploadServiceServer).UploadFile(&fileUploadServiceUploadFileServer{stream})
}

type FileUploadService_UploadFileServer interface {
	SendAndClose(*FileUploadResponse) error
	Recv() (*FileUploadRequest, error)
	grpc.ServerStream
}

type fileUploadServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *fileUploadServiceUploadFileServer) SendAndClose(m *FileUploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileUploadServiceUploadFileServer) Recv() (*FileUploadRequest, error) {
	m := new(FileUploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileUploadService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileUploadServiceServer).DownloadFile(m, &fileUploadServiceDownloadFileServer{stream})
}

type FileUploadService_DownloadFileServer interface {
	Send(*FileDownloadResponse) error
	grpc.ServerStream
}

type fileUploadServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *fileUploadServiceDownloadFileServer) Send(m *FileDownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FileUploadService_GetListFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileUploadServiceServer).GetListFiles(m, &fileUploadServiceGetListFilesServer{stream})
}

type FileUploadService_GetListFilesServer interface {
	Send(*ListFilesResponse) error
	grpc.ServerStream
}

type fileUploadServiceGetListFilesServer struct {
	grpc.ServerStream
}

func (x *fileUploadServiceGetListFilesServer) Send(m *ListFilesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// FileUploadService_ServiceDesc is the grpc.ServiceDesc for FileUploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileUploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FileUploadService",
	HandlerType: (*FileUploadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _FileUploadService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _FileUploadService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetListFiles",
			Handler:       _FileUploadService_GetListFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sending.proto",
}
